<!DOCTYPE html>
<!--
 * File : application/views/scripts/deviceprofilemanagerci/deviceciinstanceview.phtml
 * Description : Sample CI view
 * Created Date :  2015-11-18
 * Date of Change :  2016-8-30
 * Created by : Shaw Chang
 * E-mail : shaw.chang@hpe.com
 * Changed by :  Shaw Chang
 * Change log : adding new code comment section.
 * Version no. : 1.0.
-->
<html>
    <head>
        <?php
        echo $this->headLink()->appendStylesheet(PROJECT_PATH . '/public/css/jquery-ui-1.10.3.custom.min.css')
                ->appendStylesheet(PROJECT_PATH . '/public/css/styles.css')
                ->appendStylesheet(PROJECT_PATH . '/public/css/netsrm.css')
                ->appendStylesheet(PROJECT_PATH . '/public/css/form.css')
                ->appendStylesheet(PROJECT_PATH . '/public/styles/styles.css')
                ->appendStylesheet(PROJECT_PATH . '/public/css/jquery.multiselect2side.css')
                ->appendStylesheet(PROJECT_PATH . '/public/css/basic.css')
                ->appendStylesheet(PROJECT_PATH . '/public/js/tooltipster/css/tooltipster.css')

        ;
        echo $this->headScript()
                ->appendFile(PROJECT_PATH . '/public/js/jquery-1.7.2.min.js')
                ->appendFile(PROJECT_PATH . '/public/js/jquery-ui-1.10.3.custom.min.js')
                ->appendFile(PROJECT_PATH . '/public/js/jquery.multiselect2side.js')
                ->appendFile(PROJECT_PATH . '/public/js/_lib/jquery.cookie.js')
                ->appendFile(PROJECT_PATH . '/public/js/_lib/jquery.hotkeys.js')
                ->appendFile(PROJECT_PATH . '/public/js/_docs/syntax/!script.js')
                ->appendFile(PROJECT_PATH . '/public/js/background.min.js')
                ->appendFile(PROJECT_PATH . '/public/js/modal.js')
                ->appendFile(PROJECT_PATH . '/public/js/jquery.simplemodal.js')
                ->appendFile(PROJECT_PATH . '/public/js/loading.js')
                ->appendFile(PROJECT_PATH . '/public/js/basic.js');

        $field_status_img_green = SITE_URL . "public/images/solid_greendot.png";
        $field_status_img_red = SITE_URL . "public/images/solid_reddot.png";
        ?>

        <script type="text/javascript" src="<?php echo SITE_URL ?>public/js/tooltipster/js/jquery.tooltipster.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {

                $("#accordion").accordion({
                    heightStyle: "content",
                    collapsible: true,
                    active: false
                });

                $("#accordion1").accordion({
                    heightStyle: "content",
                    collapsible: true,
                    active: false
                });


                $('#message_submit').click(function (event) {
                    event.preventDefault();
                    var content = $("#body").val();
                    //          alert(content);
                    popup(content);

                });

                function popup(content1) {

                    var device_id;
                    var note = content1;
                    alert(note);


                    $.ajax({
                        type: "POST",
                        url: "<?php echo SITE_URL; ?>deviceprofilemanagerci/cinotes",
                        data: "device_id=" + '15' + " note=" + note,
                        dataType: 'json',
                        async: false

                    });

                }


                function deselect(e) {
                    $('.pop').slideFadeToggle(function () {
                        e.removeClass('selected');
                    });
                }

                $(function () {
                    $('#contact').on('click', function () {
                        if ($(this).hasClass('selected')) {
                            deselect($(this));
                        } else {
                            $(this).addClass('selected');
                            $('.pop').slideFadeToggle();
                        }
                        return false;
                    });

                    $('.close').on('click', function () {
                        deselect($('#contact'));
                        return false;
                    });
                });

                $.fn.slideFadeToggle = function (easing, callback) {
                    return this.animate({opacity: 'toggle', height: 'toggle'}, 'fast', easing, callback);
                };



                $('#device_action_item_view_mode_btn_cancel').click(function () {
                    window.location.href = '<?php echo SITE_URL ?>Deviceprofilemanagerci/manage/accounttype_id/<?php echo $this->content[0]['accounttype_id']; ?>/datasource_id/<?php echo $this->content[0]['datasource_id']; ?>';
                            });
                            $('#device_action_item_view_mode_btn_edit').click(function () {
                                window.location.href = '<?php echo SITE_URL ?>Deviceprofilemanagerci/deviceciinstanceedit/device_id/<?php echo $this->device_id; ?>';
                                        });


                                        $('#config_parser').click(function () {
                                            alert("Link to Configuration Parser456");
                                        });

                                        $('#get_realtime_configuration_id').click(function () {
                                            var ip = "<?php echo $this->content[0]['ipaddress']; ?>";
                                            var dn = "<?php echo $this->content[0]['devicename']; ?>";
                                            var device_id = "<?php echo $this->device_id; ?>";
                                            var url = "<?php echo SITE_URL; ?>deviceprofilemanagerci/testpage/ipaddress/" + ip + "/devicename/" + dn + "/device_id/" + device_id;
                                            window.open('' + url, 'mywin', 'left=20,top=20,width=500,height=500,resizable=1,scrollbars=1');
                                            window.setTimeout(function () {
                                                location.reload();
                                            }, 5000);
                                            return false;
                                        });

                                        $('#ci_activity_history_id').click(function () {
                                            var ip = $("#IP_Address").val();
                                            var dn = $("#Device_Instance_Name").val();
                                            var url = "<?php echo SITE_URL; ?>deviceprofilemanagerci/ciactivityhistory/ip/" + ip + "/dn/" + dn;
                                            window.open('' + url, 'mywin1', 'scrollbars=yes,menubar=no,left=20,top=20,width=500,height=500,resizable=yes');
                                        });

                                        $('#ci_note').click(function () {

                                            temp();

                                            function temp() {
                                                var src = "<?php echo SITE_URL ?>Deviceprofilemanagerci/cinote1/device_id/+<?php echo $this->device_id; ?>";
                                                                $.modal('<iframe src="' + src + '" height="400" width="600" style="border:0;overflow-y:hidden;overflow-x:hidden">', {
                                                                    closeHTML: "",
                                                                    modal: true,
                                                                    containerCss: {
                                                                        backgroundColor: "#fff",
                                                                        borderColor: "#000",
                                                                        height: 400,
                                                                        padding: 0,
                                                                        width: 615
                                                                    },
                                                                    overlayClose: false
                                                                }).setPosition();
                                                            }

                                                        });


                                                        $(".show_full_config").on("click", function (event) {
                                                            event.preventDefault();
                                                            var configid123 = $(this).attr('configid');
                                                            var popuphtml = $("#full_config_dialog" + configid123).html();
                                                            var new_window = window.open('', '', 'resizable=1, left=20,top=20,width=600,height=500,scrollbars=1');
                                                            var temp = new_window.document;
                                                            temp.write('<html><head><title>Configuration</title></head><body style="background-color:lightgrey;">');
                                                            temp.write(popuphtml);
                                                            temp.write('</body></html>');
                                                            temp.close();
                                                            return false;

                                                        });



                                                        $('#eng_node_term').click(function () {
                                                            window.location.href = '<?php echo SITE_URL ?>Engnodeterm/termnodeview/deviceci_ipaddr/<?php echo $this->content[0]['ipaddress']; ?>/deviceci_fqdn/<?php echo $this->content[0]['devicename']; ?>/asp_ipaddr/<?php echo $this->content[0]['hpna_ipaddr']; ?>/orgid/<?php echo $this->content[0]['accounttype_id']; ?>';
                                                                    });

                                                                    $('#run_actions').click(function () {
                                                                        window.location.href = '<?php echo SITE_URL ?>Runactionscripts/runactionform/deviceCI/<?php echo $this->content[0]['ipaddress']; ?>/org_id/<?php echo $this->content[0]['accounttype_id']; ?>';
                                                                                });

                                                                                $('.tooltip').tooltipster({
                                                                                    position: 'bottom',
                                                                                    animation: 'grow',
                                                                                    arrowColor: '#000',
                                                                                    maxWidth: 280,
                                                                                    interactive: true,
                                                                                    delay: 0,
                                                                                    content: $(this).attr("title")
                                                                                });
                                                                            });

        </script>



        <style type="text/css">
            a.selected {
                background-color:#1F75CC;
                color:white;
                z-index:100;
            }

            .messagepop {
                background-color:#FFFFFF;
                border:1px solid #999999;
                cursor:default;
                display:none;
                margin-top: 15px;
                position:absolute;
                text-align:left;
                width:394px;
                z-index:50;
                padding: 25px 25px 20px;
            }

            label {
                display: block;
                margin-bottom: 3px;
                padding-left: 15px;
                text-indent: -15px;
            }

            .messagepop p, .messagepop.div {
                border-bottom: 1px solid #EFEFEF;
                margin: 8px 0;
                padding-bottom: 8px;
            }
            .accordion_content {
                background:0px;
                padding:0px !important;
                text-align:left;
                background-color:white;
            }

            .device_action_input_block{
                display:block;
                margin-left: auto;
                margin-right: auto;
                width: auto;
                margin-top: 5px;
            }
            .nascent_label{
                display:inline-block;
                width:30%;
                float:none;
            }
            .device_action_input_block_input{
                display:inline-block;
                width:68%;
                margin-right: 0px;
            }
            .device_action_add_status_state_input{

            }
            .device_action_add_action_status_state_div{
                display:inline-block;
                width: 100px;
                margin-left:8px;
                margin-right:0px;

            }
            .device_action_add_action_block_title{

                background: black;
                color: white;
                padding: 3px;
                font-size: 18px;
                width: auto;
            }
            .device_action_add_action_status_state_div{
                display:inline-block;
                width: auto;
            }
            .device_action_add_status_state_input,.device_action_add_available_action_list{
                padding: 5px;
                width: auto;
            }
            #device_action_add_action_description{
                padding: 3px;

            }
            input[type="text"]{
                width:100%;
                padding: 5px;
                float: left;
                font-size: 20px !important;
            }
        </style>
    </head>
    <body>

        <div class="dvLoading"></div>

        <div style="padding:20px;display:table;width:96%">
            <div>    <?php echo $this->informationtooltip("47.1"); ?> </div>

            <div class="simple_btn3">
                <div style="text-align:center;padding:5px 0 0 5%;clear:both;width:90%">Device CI Instance (View)</div>
            </div>
            <div class="simple_btn">
                <div style="text-align:center;padding:3px 0 0 5%;clear:both;width:90%"><?php echo $this->content[0]['org']; ?> > <?php echo $this->content[0]['datasource']; ?> >  <?php echo $this->content[0]['devicename']; ?>  : View</div>
            </div>

            <div style='clear:both'>&nbsp;</div>
            <form id="device_action_add_new_action_form">
                <div id="form_div">
                    <input type="hidden" name="device_id" id="device_id" value="<?php echo $this->device_id; ?>" />
                    <input type="hidden" name="device_type_id" id="device_type_id" value="<?php echo $this->device_type_id; ?>" />
                    <input type="hidden" name="device_vendor_id" id="device_vendor_id" value="<?php echo $this->device_vendor_id; ?>" />
                    <input type="hidden" name="device_os_id" id="device_os_id" value="<?php echo $this->device_os_id; ?>" />
                    <input type="hidden" name="device_osv_id" id="device_osv_id" value="<?php echo $this->device_osv_id; ?>" />
<!--                  <input name="ci_note" id="ci_note" value="<?php ?>" />-->



                    <!-- first row div starts here -->

                    <div style="width:100%;display:block;">

                        <div style='clear:both;'>
                            <div style="margin-left:auto;margin-right:auto;display:inline-block;width: 48%">



                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span style='cursor:pointer;font-weight:bold;color:#000;' title="Device Instance Name"> Device Instance Name </span>
                                    </div>

                                    <div class="device_action_input_block_input">


                                        <div class="device_action_input_block_input"><input disabled type="text" id="Device_Instance_Name" name="Device_Instance_Name" class="device_action_add_row_column_input_text dot_check" 
                                                                                            value="<?php echo $this->content[0]['devicename'] ?>" ></div>
                                    </div>
                                </div>
                                <div style='clear:both'>&nbsp;</div>
                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span style='cursor:pointer;font-weight:bold;color:#000;' title="IP Address">IP Address </span> 
                                    </div>

                                    <div class="device_action_input_block_input">
                                        <div class="device_action_input_block_input"><input type="text" disabled id="IP_Address" name="IP_Address" class="device_action_add_row_column_input_text dot_check" value="<?php echo $this->content[0]['ipaddress'] ?>" ></div>
                                    </div>
                                </div>
                                <div style='clear:both'>&nbsp;</div>	

                                <!-- start -->
                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span disabled style='cursor:pointer;font-weight:bold;color:#000;' title="Organization">Organization </span>  
                                    </div>
                                    <div class="device_action_input_block_input">
                                        <div class="device_action_input_block_input"><input disabled type="text" id="device_action_add_version-3" name="Organization" class="device_action_add_row_column_input_text dot_check" value="<?php echo $this->content[0]['org'] ?>" ></div>
                                    </div>
                                </div>
                                <!-- end -->
                                <div style='clear:both'>&nbsp;</div>
                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span style='cursor:pointer;font-weight:bold;color:#000;' title="CI Data Source Name">CI Data Source Name </span>  
                                    </div>
                                    <div class="device_action_input_block_input">
                                        <div class="device_action_input_block_input"><input disabled type="text" id="device_action_add_version-4" name="Data_Source_Name" class="device_action_add_row_column_input_text dot_check" value="<?php echo $this->content[0]['datasource'] ?>" ></div>

                                    </div>
                                </div>
                                <div style='clear:both'>&nbsp;</div>
                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span style='cursor:pointer;font-weight:bold;color:#000;' title="Device Profile">Device Profile </span>  
                                    </div>
                                    <div class="device_action_input_block_input">
                                        <div class="device_action_input_block_input"><input disabled type="text" id="device_action_add_version-5" name="Device_Profile" class="device_action_add_row_column_input_text dot_check" value="<?php echo $this->content[0]['deviceprofile'] ?>" ></div>
                                    </div>
                                </div>
                                <div style='clear:both'>&nbsp;</div>
                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span style='cursor:pointer;font-weight:bold;color:#000;' title="Type">Type </span>  
                                    </div>
                                    <div class="device_action_input_block_input">
                                        <div class="device_action_input_block_input"><input disabled type="text" id="device_action_add_version-6" name="Type" class="device_action_add_row_column_input_text dot_check" value="<?php echo $this->content[0]['type'] ?>" ></div>
                                    </div>
                                </div>
                                <div style='clear:both'>&nbsp;</div>
                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span style='cursor:pointer;font-weight:bold;color:#000;' title="Vendor">Vendor </span>  
                                    </div>
                                    <div class="device_action_input_block_input">
                                        <div class="device_action_input_block_input"><input disabled type="text" id="device_action_add_version-7" name="Vendor" class="device_action_add_row_column_input_text dot_check" value="<?php echo $this->content[0]['vendor'] ?>" ></div>
                                    </div>
                                </div>
                                <div style='clear:both'>&nbsp;</div> 
                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span style='cursor:pointer;font-weight:bold;color:#000;' title="Model">Model </span>  
                                    </div>
                                    <div class="device_action_input_block_input">
                                        <div class="device_action_input_block_input"><input disabled type="text" id="device_action_add_version-8" name="Model" class="device_action_add_row_column_input_text dot_check" value="<?php echo $this->content[0]['model'] ?>" ></div>
                                    </div>
                                </div>
                                <div style='clear:both'>&nbsp;</div>
                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span style='cursor:pointer;font-weight:bold;color:#000;' title="HW Version">HW Version </span>  
                                    </div>
                                    <div class="device_action_input_block_input">
                                        <div class="device_action_input_block_input"><input disabled type="text" id="device_action_add_version-9" name="HW_Version" class="device_action_add_row_column_input_text dot_check" value="<?php echo $this->content[0]['modelversion'] ?>" ></div>
                                    </div>
                                </div>
                                <div style='clear:both'>&nbsp;</div>
                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span style='cursor:pointer;font-weight:bold;color:#000;' title="HW Version">HW Version Revision </span>  
                                    </div>
                                    <div class="device_action_input_block_input">
                                        <div class="device_action_input_block_input"><input disabled type="text" id="device_action_add_version-10" name="HW_Version" class="device_action_add_row_column_input_text dot_check" value="<?php echo $this->content[0]['modelversionrevision'] ?>" ></div>
                                    </div>
                                </div>
                                <div style='clear:both'>&nbsp;</div>
                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span style='cursor:pointer;font-weight:bold;color:#000;' title="OS">OS </span>  
                                    </div>
                                    <div class="device_action_input_block_input">
                                        <div class="device_action_input_block_input"><input disabled type="text" id="device_action_add_version-11" name="OS" class="device_action_add_row_column_input_text dot_check" value="<?php echo $this->content[0]['os'] ?>" ></div>
                                    </div>
                                </div>
                                <div style='clear:both'>&nbsp;</div>
                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span style='cursor:pointer;font-weight:bold;color:#000;' title="OS Ver">OS Version </span>  
                                    </div>
                                    <div class="device_action_input_block_input">
                                        <div class="device_action_input_block_input"><input disabled type="text" id="device_action_add_version-12" name="OS_Ver" class="device_action_add_row_column_input_text dot_check" value="<?php echo $this->content[0]['osversion'] ?>" ></div>
                                    </div>
                                </div>
                                <div style='clear:both'>&nbsp;</div>
                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span style='cursor:pointer;font-weight:bold;color:#000;' title="OS Release">OS Release </span>  
                                    </div>
                                    <div class="device_action_input_block_input">
                                        <div class="device_action_input_block_input"><input disabled type="text" id="device_action_add_version-13" name="OS_Release" class="device_action_add_row_column_input_text dot_check" value="<?php echo $this->content[0]['osversionrevision'] ?>" ></div>
                                    </div>
                                </div>

                                <div style='clear:both'>&nbsp;</div>
                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span style='cursor:pointer;font-weight:bold;color:#000;' title="Device Instance Function">Managing ASP Instance</span>  
                                    </div>
                                    <div class="device_action_input_block_input">
                                        <div class="device_action_input_block_input"><input disabled type="text" id="device_action_add_version-14" name="Device_Instance_Function" class="device_action_add_row_column_input_text dot_check" value="<?php echo $this->content[0]['hpna'] ?>" ></div>
                                    </div>
                                </div>
                                <div style='clear:both'>&nbsp;</div>
                                <div class="device_action_input_block">
                                    <div class="nascent_label" >
                                        <span style='cursor:pointer;font-weight:bold;color:#000;' title="Device Instance Function">Device Instance Function </span>  
                                    </div>
                                    <div class="device_action_input_block_input">
                                        <div class="device_action_input_block_input"><input disabled type="text" id="device_action_add_version-15" name="Device_Instance_Function" class="device_action_add_row_column_input_text dot_check" value="<?php echo $this->content[0]['datasource'] ?>" ></div>
                                    </div>
                                </div>

                            </div>



                            <div style="margin-left:auto;margin-right:auto;display:inline-block;width: 48%;height: 100%;vertical-align: top;">
                                <div>       
                                    <a href="javascript:void(0);" id="eng_node_term" class="hp-button hp-primary" style='float:left' >Open Engineering Node Terminal</a>
                                    <a href="javascript:void(0);" id="get_realtime_configuration_id" class="hp-button hp-primary" style='float:left' >Get Realtime Configuration</a>

                                    <a href="javascript:void(0);" id="ci_activity_history_id" class="hp-button hp-primary" style='float:left' >CI Activity History</a>
                                    <!--<a href="javascript:void(0);" id="ci_note" class="hp-button hp-primary" style='float:left' >CI NOTE 1234</a>-->


                                    <a id="ci_note" class="hp-button hp-primary" style='float:left' >CI NOTE</a>              
                                </div>
                                <br> <br><br>
                                <div style="text-align:left" class="device_action_add_action_block_title">Device Description </div>
                                <div style="text-align:left"><textarea disabled rows="12" id="device_action_add_action_description" name="device_description" style="width:100%;" ><?php echo $this->content[0]['description'] ?></textarea></div>
                                <br>
                                <div style="text-align:left" class="device_action_add_action_block_title">Current Configurations </div>
                                <div style="text-align:left"><textarea disabled rows="12" id="device_action_add_action_description" name="Current_Configurations" style="width:100%;" readonly ></textarea></div>
                                <br>

                                <div id="accordion1" style="float:left;width:100%" >
                                    <div>Available Automation Actions</div>

                                    <iframe src="<?php echo SITE_URL; ?>Deviceprofilemanagerci/gridiframe/device_id/<?php echo $this->device_id; ?>" height="500" style="border:2px;width:100%"> </iframe> 

                                </div>
                                <br>
                                <div id="accordion" style="float:left;width:100%" >
                                    <div>Device CI Configurations</div>
                                    <iframe src="<?php echo SITE_URL; ?>Deviceprofilemanagerci/gridiframerealtime/device_id/<?php echo $this->device_id; ?>" height="500" style="border:2px;width:100%"> </iframe> 
                                </div>
                            </div>
                            <br><br>

                        </div>

                    </div>

                    <div style='clear:both'>&nbsp;</div>

                </div>
            </form>
            <div class="netsrm_box" align="" style="width:99%;display:table;padding:5px;">
                <a href="javascript:void(0);" class="hp-button hp-critical" style='float:left' id="device_action_item_view_mode_btn_edit" >Edit</a>
                <a href="javascript:void(0);" class="hp-button hp-disabled" style='float:left' id="device_action_item_view_mode_btn_cancel" >Cancel</a>


            </div>
        </div>

        <?php foreach ($this->configurations as $config) { ?>  
            <div style="display:none;" id="full_config_dialog<?php echo $config['id']; ?>" >
                <div class="netsrm_box" style="">
                    <div>
                        <h1><?php echo $this->content[0]['devicename'] ?></h1>
                        <h3>IP:  <?php echo $this->content[0]['ipaddress'] ?> </h3>
                        <h3>Timestamp: <?php echo $config['timestamp']; ?> </h3>
                        <h3>Full Configuration</h3>  
                        <a href="#" onclick="window.close();" style="position:absolute;right:10px;top:10px;"><img src="<?php echo SITE_URL; ?>/public/images/NetSRM Icons/Launch Page Icons/Critical Icons/cancel.png"></a>
                        <div style="clear:both;"></div>
                    </div>

                    <div>
                        <textarea class="netsrm_box" style="border: 1px solid #ccc; font-size:21px !important; width:100%;height:100%; top:116px;">
                            <?php echo $config['text']; ?>
                        </textarea>
                        <br> <br> <br>
                    </div>
                </div>
            </div> 
        <?php } ?>

    </body>
</html>